set_property SRC_FILE_INFO {cfile:C:/Users/huang/Desktop/7020/1_led/prj/led.srcs/constrs_1/new/led.xdc rfile:../../../led.srcs/constrs_1/new/led.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L14 IOSTANDARD LVCMOS33} [get_ports key]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports led]
